# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-chunkserver

COMMENT=	MooseFS data storage and synchronization component

LICENSE=	GPLv2

MFS_COMPONENT=	chunkserver

MASTERDIR=	${.CURDIR}/../moosefs2-master

.include "${MASTERDIR}/Makefile"
