# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>

PKGNAMESUFFIX=	-gui

COMMENT=	MooseFS web-based GUI

LICENSE=	GPLv2

MFS_COMPONENT=	gui

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
