# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-chunkserver

COMMENT=	Storing files data and synchronizing it among themselves

LICENSE=	GPLv2

MFS_COMPONENT=	chunkserver

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
