PORTREVISION=	0
PKGNAMESUFFIX=	-${MFS_COMPONENT}

COMMENT=	MooseFS data storage and synchronization component

MFS_COMPONENT=	chunkserver

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
