# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-netdump

COMMENT=	MooseFS network packet dump utility

LICENSE=	GPLv2

MFS_COMPONENT=	netdump

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
