share/mfscgi/mfs.cgi
share/mfscgi/mfs.css
share/mfscgi/mfsgraph.py
share/mfscgi/logo.svg
share/mfscgi/logopro.svg
share/mfscgi/index.html
share/mfscgi/err.gif
share/mfscgi/chart.cgi
share/mfscgi/chartdata.cgi
share/mfscgi/favicon.ico
share/mfscgi/cgiscripts.js
share/mfscgi/acidchart.js
share/mfscgi/acidtab.js
