.TH mfschunkdbdump "8" "December 2025" "MooseFS 4.58.3-1" "This is part of MooseFS"
.ss 12 0
.SH NAME
mfschunkdbdump \- dumps data stored by a chunkserver in a chunkdb file
.SH SYNOPSIS
.B mfschunkdbdump \fIchunkdb_filename\fP
.SH DESCRIPTION
.PP
\fBmfschunkdbdump\fP dumps data, stored by a chunkserver in a chunkdb file, into human-readable (txt) format.
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2025 Jakub Kruszona-Zawadzki, Saglabs SA

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see
<https://www.gnu.org/licenses/>.
.SH "SEE ALSO"
.BR mfschunkserver (8)
