.TH mfschunkserver.cfg "5" "May 2015" "MooseFS 2.0.68-1" "This is part of MooseFS"
.SH NAME
mfschunkserver.cfg \- main configuration file for \fBmfschunkserver\fP
.SH DESCRIPTION
The file \fBmfschunkserver.cfg\fP contains configuration of MooseFS
chunkserver process.
.SH SYNTAX
.PP
Syntax is:
.TP
\fIOPTION\fP \fB=\fP \fIVALUE\fP
.PP
Lines starting with \fB#\fP character are ignored as comments.
.SH OPTIONS
Configuration options:
.TP
\fBWORKING_USER\fP
user to run daemon as
.TP
\fBWORKING_GROUP\fP
group to run daemon as; optional value - if empty then default user group will be used
.TP
\fBSYSLOG_IDENT\fP
name of process to place in syslog messages; default is mfschunkserver
.TP
\fBLOCK_MEMORY\fP
whether to perform mlockall() to avoid swapping out mfschunkserver process; default is 0, i.e. no
.TP
\fBNICE_LEVEL\fP
nice level to run daemon with; default is -19; note: process must be started as root to increase priority, if setting of priority fails, process retains the nice level it started with
.TP
\fBFILE_UMASK\fP
set default umask for group and others (user has always 0); default is 027 - block write for group and block all for others
.TP
\fBDATA_PATH\fP
where to store daemon lock file
.TP
\fBHDD_CONF_FILENAME\fP
alternate location/name of \fBmfshdd.cfg\fP file
.TP
\fBHDD_TEST_FREQ\fP
chunk test period in seconds; default is 10
.TP
\fBHDD_LEAVE_SPACE_DEFAULT\fP
how much space should be left unused on each hard drive; 
number format: [0-9]*(.[0-9]*)?([kMGTPE]|[KMGTPE]i)?B? ; default is 256MiB; 
examples: 0.5GB, .5G, 2.56GiB, 1256M etc.
.TP
\fBHDD_REBALANCE_UTILIZATION\fP
percent of total work time the chunkserver is allowed to spend on hdd space rebalancing; default is 20
.TP
\fBHDD_ERROR_TOLERANCE_COUNT\fP,\fBHDD_ERROR_TOLERANCE_PERIOD\fP
how many i/o errors (COUNT) to tolerate in given amount of seconds (PERIOD) on a single hard drive; if the number of errors exceeds this setting, the offending hard drive will be marked as damaged; defaults are 2 and 600
.TP
\fBHDD_FSYNC_BEFORE_CLOSE\fP
enables/disables fsync before chunk closing; deafult is 0 (off)
.TP
\fBWORKERS_MAX\fP,\fBWORKERS_MAX_IDLE\fP
maximum number of active workers and maximum number of idle workers; defaults are 150 and 40
.TP
\fBBIND_HOST\fB
local address to use for master connections; default is *, i.e. default local address
.TP
\fBMASTER_HOST\fP
MooseFS master host, IP is allowed only in single-master installations; default is mfsmaster
.TP
\fBMASTER_PORT\fP
MooseFS master command port; default is 9420
.TP
\fBMASTER_CONTROL_PORT\fP
MooseFS master control port; default is 9419
.TP
\fBMASTER_TIMEOUT\fP
timeout in seconds for master connections; default is 60
.TP
\fBMASTER_RECONNECTION_DELAY\fP
delay in seconds before trying to reconnect to master after disconnection (default is 5)
.TP
\fBBIND_HOST\fP
local address to use for connecting with master (default is \fB*\fP, i.e. default local address)
.TP
\fBCSSERV_LISTEN_HOST\fP
IP address to listen on for client (mount) connections (\fB*\fP means any)
.TP
\fBCSSERV_LISTEN_PORT\fP
port to listen on for client (mount) connections (default is 9422)
.TP
\fBCSSERV_TIMEOUT\fP
timeout (in seconds) for client (mount) connections (default is 5)
.SH COPYRIGHT
Copyright (C) 2015 Jakub Kruszona-Zawadzki, Core Technology Sp. z o.o.

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfschunkserver (8),
.BR mfshdd.cfg (5)
