.TH mfseattr "1" "October 2025" "MooseFS 4.58.1-1" "This is part of MooseFS"
.ss 12 0
.SH NAME
mfseattr \- \fBMooseFS\fP extra attributes management tools
.SH SYNOPSIS
.B mfsgeteattr
[\fB-?\fP] [\fB-r\fP] [\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] \fIOBJECT\fP...
.PP
.B mfsseteattr
[\fB-?\fP] [\fB-r\fP] [\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] \fB-f\fP \fIATTRNAME\fP [\fB-f\fP \fIATTRNAME\fP ...] \fIOBJECT\fP...
.PP
.B mfsdeleattr
[\fB-?\fP] [\fB-r\fP] [\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] \fB-a\fP | \fB-f\fP \fIATTRNAME\fP [\fB-f\fP \fIATTRNAME\fP ...] \fIOBJECT\fP...
.PP
.B mfscopyeattr
[\fB-?\fP] [\fB-r\fP] [\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] \fISOURCE_OBJECT\fP \fIOBJECT\fP...
.SH DESCRIPTION
These tools are used to get, set or delete some extra attributes (flags).
.PP
\fBmfsgeteattr\fP displays extra attributes of specified object. If \fB-r\fP option is used, the tool will display statistics for 
all attributes usage across the whole directory tree specified by \fIOBJECT\fP.
.PP
\fBmfsseteattr\fP sets attribute specified by \fB-f\fP. Option \fB-f\fP can be used more than once, so that
several attributes can be set with one command. If \fB-r\fP option is used, specified attributes will be set
recursively.
.PP
\fBmfsdeleattr\fP deletes (clears) attribute specified by \fB-f\fP. Option \fB-f\fP can be used more than once, so that
several attributes can be deleted with one command. Alternatively, \fB-a\fP option can be used to delete all existing extra attributes. 
If \fB-r\fP option is used, specified attributes will be deleted recursively.
.PP
\fBmfscopyeattr\fP copies the current set of attributes of \fISOURCE_OBJECT\fP to \fIOBJECT\fP. 
This is an exact copy, so any attributes that \fIOBJECT\fP has, but \fISOURCE_OBJECT\fP doesn't, will be cleared.
If \fB-r\fP option is used, attributes will be copied recursively.
.SH OPTIONS
.SS ATTRIBUTES
.PP
\fBnoowner\fP This flag means,
that particular object belongs to current user (\fIuid\fP and \fIgid\fP are equal
to \fIuid\fP and \fIgid\fP values of accessing process). Only root (\fIuid\fP=0)
sees the real \fIuid\fP and \fIgid\fP.
.PP
\fBnoattrcache\fP This flag means, that standard file attributes such as uid, gid,
mode, length and so on won't be stored in kernel cache.
.PP
\fBnoentrycache\fP This flag is similar to above. It prevents directory entries
from being cached in kernel.
.PP
\fBnodatacache\fP This flag means, that data should never be kept in kernel cache (similar to O_DIRECT open flag).
.PP
\fBsnapshot\fP This flag means that the object was created via a \fBmfsmakesnapshot\fP command
.PP
\fBundeletable\fP This flag prevents unlinking (admin only; not inherited)
.PP
\fBappendonly\fP Object with this flag can only be appended to, unlinking and other modifications are not allowed (admin only; not inherited)
.PP
\fBimmutable\fP This flag prevents any change to given object (admin only; not inherited)
.SS GENERAL OPTIONS
Most \fBMooseFS\fP tools use \fB-n\fP, \fB-h\fP, \fB-H\fP, \fB-k\fP, \fB-m\fP and \fB-g\fP
options to select
format of printed numbers. \fB-n\fP causes to print exact numbers, \fB-h\fP
uses binary prefixes (Ki, Mi, Gi as 2^10, 2^20 etc.) while \fB-H\fP uses SI
prefixes (k, M, G as 10^3, 10^6 etc.). \fB-k\fP, \fB-m\fP and \fB-g\fP show plain numbers
respectivaly in kibis (binary kilo - 1024), mebis (binary mega - 1024^2)
and gibis (binary giga - 1024^3).
The same can be achieved by setting
\fBMFSHRFORMAT\fP environment variable to: \fB0\fP (exact numbers), \fB1\fP
or \fBh\fP (binary prefixes), \fB2\fP or \fBH\fP (SI prefixes), \fB3\fP or
\fBh+\fP (exact numbers and binary prefixes), \fB4\fP or \fBH+\fP (exact
numbers and SI prefixes). The default is to print just exact numbers.
.PP
Option \fB-?\fP displays short usage message.
.SH NOTES
.SS INHERITANCE
When a new object is created in MooseFS, extra attributes are inherited from the parent directory. A newly created
object inherits always the current set of its parent's attributes. Changing a
directory attribute does not affect its already created children. To change
an attribute for a directory and all of its children use \fB-r\fP option.

.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2025 Jakub Kruszona-Zawadzki, Saglabs SA

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfsmount (8),
.BR mfstools (1),
.BR mfssnapshots (1)
