.TH mfshdd.cfg "5" "October 2020" "MooseFS 3.0.115-1" "This is part of MooseFS"
.SH NAME
mfshdd.cfg \- list of MooseFS storage directories for \fBmfschunkserver\fP
.SH DESCRIPTION
The file \fBmfshdd.cfg\fP contains list of directories (mountpoints)
used for MooseFS storage.
.SH SYNTAX
.PP
Syntax is:
.TP
[\fB*\fP|\fB<\fP|\fB>\fP|\fB~\fP]\fIPATH\fP [\fISPACE LIMIT\fP]
.PP
Lines starting with \fB#\fP character are ignored as comments.
.PP
Path can be prefixed with one or more special characters. These characters work as additional options.
.RS
.IP \fB*\fP
means this directory (hard drive) is "marked for removal" 
and all data will be replicated to other hard drives, usually on other chunkservers
.IP \fB<\fP
means that all data from this hard drive should be moved to other local hard drives
.IP \fB>\fP
means that all data from other local hard drives should be moved to this hard drive
.IP \fB~\fP
means that significant (more than 10% in less than minute) change of total blocks count will not mark this drive as damaged (useful for compressed filesystems)
.RE
.PP
\fIPATH\fP is path to the mounting point of storage directory, usually a single hard drive.
.PP
\fISPACE LIMIT\fP is optional space limit, that allows to set one of two values: 
how much space should be left unused on this device or how much space is to be used on this device.
Definition format: [0-9]*(.[0-9]*)?([kMGTPE]|[KMGTPE]i)?B?, positive value means 
how much space to use, negative value means how much space should be left unused.
.SH COPYRIGHT
Copyright (C) 2020 Jakub Kruszona-Zawadzki, Core Technology Sp. z o.o.

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfschunkserver (8),
.BR mfschunkserver.cfg (5)
