.TH mfsmaster "8" "January 2025" "MooseFS 4.57.1-1" "This is part of MooseFS"
.SH NAME
mfsmaster \- start, restart or stop MooseFS master process
.SH SYNOPSIS
.B mfsmaster
[\fB\-c\fP \fICFGFILE\fP]
[\fB\-f\fP]
[\fB\-d\fP]
[\fB\-u\fP]
[\fB\-n\fP]
[\fB\-i\fP]
[\fB\-a\fP]
[\fB\-e\fP]
[\fB\-x\fP[\fBx\fP]]
[\fB\-t\fP \fILOCKTIMEOUT\fP]
[\fIACTION\fP]
.PP
.B mfsmaster \-v
.PP
.B mfsmaster \-h
.SH DESCRIPTION
.PP
\fBmfsmaster\fP is the master program of MooseFS.
.SH OPTIONS
.TP
\fB\-v\fP
print version information and exit
.TP
\fB\-h\fP
print usage information and exit
.TP
\fB\-c\fP \fICFGFILE\fP
specify alternative path of configuration file (default is
\fBmfsmaster.cfg\fP in system configuration directory)
.TP
\fB\-f\fP
run in foreground, don't daemonize
.TP
\fB\-d\fP
run with dangerous options (names: DANGEROUS_*)
.TP
\fB\-u\fP
log undefined configuration values (when default is assumed)
.TP
\fB\-n\fP
do not attempt to increase limit of core dump size
.TP
\fB\-i\fP
ignore some metadata structure errors
.TP
\fB\-a\fP
automatically restore metadata from change logs
.TP
\fB\-e\fP
(pro only) start without metadata (used to start additional masters)
.TP
\fB\-x\fP
produce more verbose output
.TP
\fB\-xx\fP
even more verbose output
.TP
\fB\-t\fP \fILOCKTIMEOUT\fP
how long to wait for lockfile (in seconds; default is 1800 seconds)
.TP
\fIACTION\fP
tells master to perform one of the following actions:
.RS 
.IP start 9
Start master process if the process is not already running, otherwise display error message.
.IP stop 
Stop master process if the process is running, otherwise display error message.
.IP restart 
(default action) If the master process is running, restart it, if it's not running, start it. 
.IP reload
Send a signal to master process to reload config files.
.IP info
Send a singal to master process to dump debug information file in working directory.
.IP test
Displays "mfsmaster pid: PID" if the master is running (and return 0) or  "mfsmaster is not running" otherwise (and return 1).
.IP kill
Send termination signal to master process.
.IP restore
Restore current metadata file using backup metadata and changlog files (if possible, i.e. if correct files exist), write it to working directory and exit.
.RE
.SH FILES
.TP
\fBmfsmaster.cfg\fP
configuration file for MooseFS master process; refer to \fBmfsmaster.cfg\fP\|(5) manual for details
.TP
\fBmfsexports.cfg\fP
MooseFS access control file; refer to
\fBmfsexports.cfg\fP\|(5) manual for details
.TP
\fBmfstopology.cfg\fP
Network topology definitions; refer to \fBmfstopology.cfg\fP\|(5) manual for details
.TP
.BR .mfsmaster.lock
lock file of running MooseFS master process
(created in data directory)
.TP
\fBmetadata.mfs\fP, \fBmetadata\.mfs\.back\fP
MooseFS filesystem metadata image (created in data directory)
.TP
\fBchangelog.\fP*\fB.mfs\fP
MooseFS filesystem metadata change logs (created in data directory; merged into \fBmetadata.mfs\fP once per hour)
.TP
\fBdata.stats\fP
MooseFS master charts state (created in data directory)
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2025 Jakub Kruszona-Zawadzki, Saglabs SA

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfschunkserver (8),
.BR mfsmount (8),
.BR mfsmaster.cfg (5),
.BR mfsexports.cfg (5),
.BR mfstopology.cfg (5)
