.TH mfsmetalogger "8" "February 2025" "MooseFS 4.57.5-1" "This is part of MooseFS"
.SH NAME
mfsmetalogger \- start, restart or stop MooseFS metalogger process
.SH SYNOPSIS
.B mfsmetalogger
[\fB\-c\fP \fICFGFILE\fP]
[\fB\-f\fP]
[\fB\-d\fP]
[\fB\-u\fP]
[\fB\-n\fP]
[\fB\-t\fP \fILOCKTIMEOUT\fP]
[\fIACTION\fP]
.PP
.B mfsmetalogger \-v
.PP
.B mfsmetalogger \-h
.SH DESCRIPTION
.PP
\fBmfsmetalogger\fP is the metadata replication server of MooseFS.
.SH OPTIONS
.TP
\fB\-v\fP
print version information and exit
.TP
\fB\-h\fP
print usage information and exit
.TP
\fB\-c\fP \fICFGFILE\fP
specify alternative path of configuration file (default is
\fBmfsmetalogger.cfg\fP in system configuration directory)
.TP
\fB\-f\fP
run in foreground, don't daemonize
.TP
\fB\-d\fP
run with dangerous options (names: DANGEROUS_*)
.TP
\fB\-u\fP
log undefined configuration values (when default is assumed)
.TP
\fB\-n\fP
do not attempt to increase limit of core dump size
.TP
\fB\-t\fP \fILOCKTIMEOUT\fP
how long to wait for lockfile (in seconds; default is 60 seconds)
.TP
\fIACTION\fP
tells metalogger to perform one of the following actions:
.RS 
.IP start 9
Start metalogger process if the process is not already running, otherwise display error message.
.IP stop 
Stop metalogger process if the process is running, otherwise display error message.
.IP restart 
(default action) If the metalogger process is running, restart it, if it's not running, start it. 
.IP reload
Send a signal to metalogger process to reload config files.
.IP info
Send a singal to metalogger process to dump debug information file in working directory.
.IP test
Displays "mfsmetalogger pid: PID" if the metalogger is running (and return 0) or  "mfsmetalogger is not running" otherwise (and return 1).
.IP kill
Send termination signal to metalogger process.
.IP restore
Not implemented.
.RE
.SH FILES
.TP
\fBmfsmetalogger.cfg\fP
configuration file for MooseFS metalogger process; refer to
\fBmfsmetalogger.cfg\fI\|(5) manual for details
.TP
\fBmfsmetalogger.lock\fP
PID file of running MooseFS metalogger process
(created in RUN_PATH by MooseFS < 1.6.9)
.TP
.BR .mfsmetalogger.lock
lock file of running MooseFS metalogger process
(created in data directory since MooseFS 1.6.9)
.TP
\fBchangelog_ml.\fP*\fB.mfs\fP
MooseFS filesystem metadata change logs (backup of master change log files)
.TP
\fBmetadata.ml.mfs.back\fP
Latest copy of complete metadata.mfs.back file from MooseFS master.
.TP
\fBsessions.ml.mfs\fP
Latest copy of sessions.mfs file from MooseFS master.
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2025 Jakub Kruszona-Zawadzki, Saglabs SA

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfsmaster (8),
.BR mfsmetalogger.cfg (5)
