.TH mfsmetadump "8" "October 2020" "MooseFS 3.0.115-1" "This is part of MooseFS"
.SH NAME
mfsmetadump - dump MooseFS metadata info in human readable format
.SH SYNOPSIS
\fBmfsmetadump\fP [\fB-d\fP] [\fB\-s\fP \fIsection_name\fP] \fImetadata_file\fP
.SH DESCRIPTION
\fBmfsmetadump\fP dumps MooseFS metadata info in human readable format. 
Output consists of several sections with different types of information. Every section consist
of header data - rows starting with hash (#) sign - and content data (may be empty). 
.SH OPTIONS
.PP
\fB-d\fP - replace all non-printable characters (codes < 32 and > 126) with '.' (it was
default behaviour in version < 3.0.110).
.PP
\fB-s\fP - dump only specified section of the file. Possible sections:
.nf
.ta +0.5i
	HEAD - header info
	SESS - client sessions
	LABS - labels (not used)
	SCLA - storage classes
	NODE - tree nodes (i-nodes)
	EDGE - tree edges (file names)
	FREE - free nodes (deleted i-nodes)
	QUOT - quota definitions
	XATR - xattr data
	PACL - posix acl data
	OPEN - open files
	FLCK - flock data
	PLCK - posix locks (lockf,ioctl) data
	CSDB - active chunkservers
	CHNK - chunks
.fi
.SH SECTION HEADER (precedes each section except HEAD)
.TP 20
section header 
section header (section type + version)
.TP
length
length of section
.TP
section type
name of section
.TP
version
hexadecimal representation of section version
.SH FILE HEADER (HEAD)
.TP 20
header
MooseFS version
.TP
version
metadata file version
.TP
fileid
metadata file id
.SH SESSIONS SECTION (SESS)
.TP 20
nextsessionid
first free session id
.TP
statscount
number of stats remembered in each session
.TP 20
SESSION
line describing a single session
.nf
.ta +1i
s	session id
e	exports checksum
p	IP address
r	root inode number
f	session flags
u	umask
g	min and max goal (redundancy level)
t	min and max trash retention
m	maproot uid,gid and mapall uid,gid
x	disabled operations
d	disconnection time (optional)
c	current hour stats data
l	last hour stats data
i	session name (usually local mount point)
.fi
.SH STORAGE CLASS SECTION (SCLA), formerly LABELS SECTION (LABS)
.TP 20
LABELDESC
line with label description (existed only in LABS)
.nf
.ta +1i
l	label letter
n	label description
.fi
.TP 20
SCLASS
(formerly LABELSET) line with storage class used in system
.nf
.ta +1i
#	storage class id
x	admin only
m	mode
d	arch delay
c	create labels
k	keep labels
a	archive labels
n	name
.fi
.SH NODES SECTION (NODE)
.TP 20
maxinode
maximum inode number used by system
.TP
hashelements
number of inodes in hash tabble
.TP 20
NODE 
line with node (inode) description
.nf
.ta +1i +1i
k	node type (-,D,S,F,B,C,L,T,R)
	-	file
	D	directory
	S	socket
	F	fifo
	B	block device
	C	character device
	L	symbolic link
	T	trash file
	R	sustained file (removed open file)
i	inode number
#	storage class id
e	flags (extra mfs attributes)
w	windows attributes
m	mode
u	uid
g	gid
a,m,c	atime, mtime, ctime
t	trash retention
d	rdevhi,rdevlo (only block and character devices)
p	path (only symbolic links)
l	file length (only files)
c	chunk list (only files)
r	sessions that have this file open (only files)
.fi
.SH EDGES SECTION (EDGE)
.TP 20
nextedgeid
next available edge id (descending)
.TP 20
EDGE
line with edge description
.nf
.ta +1i
p	parent inode number
c	child inode number
i	edge id
n	edge name
.fi
.SH FREE NODES SECTION (FREE)
.TP 20
free nodes
number of free (reusable) nodes
.TP 20
FREEID
line with free inode description
.nf
.ta +1i
i	inode number
f	deletion timestamp
.fi
.SH QUOTA SECTION (QUOT)
.TP 20
quota nodes
number of nodes with quota
.TP 20
QUOTA
line with quota description
.nf
.ta +1i
i	inode number
g	grace period
e	exceeded
f	flags
s	soft quota exceeded timestamp
si	soft inode quota
hi	hard inode quota
sl	soft length quota
hl	hard length quota
ss	soft size quota
hs	hard size quota
sr	soft real size quota
hr	hard real size quota
.fi
.SH XATTR SECTION (XATR)
.TP 20
XATTR
line with xattr description
.nf
.ta +1i
i	inode number
n	xattr name
v	xattr value
.fi
.SH POSIX ACL SECTION (PACL)
.TP 20
POSIXACL
line with acl description
.nf
.ta +1i
i	inode number
t	acl type
u	user (file owner) permissions
g	group permissions
o	other permissions
m	permission mask
n	named permissions - list of objects:
u(U):P	permissions \fIP\fP for user with uid \fIU\fP
g(G):P	permissions \fIP\fP for group with gid \fIG\fP
.fi
.SH OPEN FILES SECTION (OPEN)
.TP 20
OPENFILE
line with open file description
.nf
.ta +1i
s	session id
i	inode number
.fi
.SH FLOCK LOCK SECTION (FLCK)
.TP 20
FLOCK
line with flock-lock description
.nf
.ta +1i
i	inode number
s	session id
o	lock owner (FUSE lock owner)
t	lock type ('R' - shared lock, 'W' - exclusive lock)
.fi
.SH POSIX LOCK SECTION (PLCK)
.TP 20
POSIXLOCK
line with posix-lock description
.nf
.ta +1i
i	inode number
s	session id
o	lock owner (FUSE lock owner)
p	local process id (owner pid)
r	lock range in format <\fISTART\fP,\fIEND\fP)
t	lock type ('R' - shared lock, 'W' - exclusive lock)
.fi
.SH CHUNKSERVERS SECTION (CSDB)
.TP 20
chunk servers
number of chunkservers
.TP 20
CHUNCKSERVER
line with chunk server description
.nf
.ta +1i
i	server ip
p	server port
#	server id
m	maintenance mode
t	maintenance timeout timestamp
.fi
.SH CHUNKS SECTION (CHNK)
.TP 20
nextchunkid
first available chunk number
.TP 20
CHUNK
line with chunk description
.nf
.ta +1i
i	chunk number
v	chunk version
t	"locked to" timestamp
a	archive flag
.fi
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2020 Jakub Kruszona-Zawadzki, Core Technology Sp. z o.o.

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfsmaster (8)
