.TH mfsnetdump "8" "July 2020" "MooseFS 3.0.114-1" "This is part of MooseFS"
.SH NAME
mfsnetdump \- dump network traffic as mfs packets
.SH SYNOPSIS
.B mfsnetdump
[\fB\-r\fP \fIPCAP_FILE\fP]
[\fB\-i\fP \fIINTERFACE\fP]
[\fB\-p\fP \fIPORT_RANGE\fP]
[\fB\-f\fP \fIPCAP_FILTER\fP]
[\fB\-c\fP \fIPCOUNT\fP]
[\fB\-s\fP \fIMBYTES\fP]
[\fB\-e\fP \fICOMMANDS\fP]
[\fB\-o\fP \fICOMMANDS\fP]
[\fB\-x\fP] [\fB\-y\fP] [\fB\-n\fP]
.PP
.SH DESCRIPTION
.PP
\fBmfsnetdump\fP is an internal diagnostic tool similar to tcpdump, but specialized for MooseFS.
.SH OPTIONS
.TP
\fB\-r\fP
specify PCAP file to read packets from
.TP
\fB\-i\fP
dump packets using given network interface
.TP
\fB\-p\fP
show only packets from given port range (default range is 9419-9422, so by default only MFS packets are shown)
.TP
\fB\-f\fP
define pcap filter to filter packets
.TP
\fB\-c\fP
dump only \fIPCOUNT\fP packets and exit
.TP
\fB\-s\fP
dump only first \fIMBYTES\fP bytes of each packet
.TP
\fB\-e\fP
do not display given commands
.TP
\fB\-o\fP
show only given commands
.TP
\fB\-x\fP
do not display mfs maintenance commands (such as CSTOMA_SPACE or CLTOMA_FUSE_TIME_SYNC)
.TP
\fB\-y\fP
do not display open/close connections packets
.TP
\fB\-n\fP
show ANTOAN_NOP command (disabled by default)
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2020 Jakub Kruszona-Zawadzki, Core Technology Sp. z o.o.

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
