.TH mfsquota "1" "May 2020" "MooseFS 3.0.114-1" "This is part of MooseFS"
.SH NAME
mfsquota \- \fBMooseFS\fP quota management tools
.SH SYNOPSIS
.B mfsgetquota
[\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] 
\fIDIRECTORY\fP...
.PP
.B mfssetquota
[\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] [\fB-p\fP \fIgrace_period\fP] [\fB-i\fP|\fB-I\fP \fIinodes\fP] 
[\fB-l\fP|\fB-L\fP \fIlength\fP] [\fB-s\fP|\fB-S\fP \fIsize\fP] [\fB-r\fP|\fB-R\fP \fIrealsize\fP]
\fIDIRECTORY\fP...
.PP
.B mfsdelquota
[\fB-a\fP|\fB-A\fP|\fB-i\fP|\fB-I\fP|\fB-l\fP|\fB-L\fP|\fB-s\fP|\fB-S\fP|\fB-r\fP|\fB-R\fP]
[\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] \fB-f\fP \fIDIRECTORY\fP...
.PP
.B mfscopyquota
[\fB-n\fP|\fB-h\fP|\fB-H\fP|\fB-k\fP|\fB-m\fP|\fB-g\fP] \fISOURCE_DIRECTORY\fP \fIDESTINATION_DIRECTORY\fP
.SH DESCRIPTION
These tools are used to check, define and delete quotas. Quota is set on a directory. It can be set in one
of 4 ways: for number of inodes inside the directory (total sum of the
subtree's inodes) with \fB-i\fP, \fB-I\fP options, for sum of (logical) file lengths with
\fB-l\fP, \fB-L\fP options,
for sum of chunk sizes (not considering goals) with \fB-s\fP, \fB-S\fP options and for physical
hdd space (more or less chunk sizes multiplied by goal of each chunk) with \fB-r\fP, \fB-R\fP options.
Small letters set soft quota, capital letters set hard quota. \fB-a\fP and \fB-A\fP options in
\fBmfsdelquota\fP mean all kinds of quota. Quota behaviour is described below.
For soft quota grace period can be defined using \fB-p\fP option. When grace period is not given then
default value will be used (option defined in mfsmaster.cfg or seven days if it's not defined there).
.PP
Quota is always set on a directory. Hard quota cannot be exceeded anytime.
Soft quota can be exceeded for a specified period of time. Once a quota is exceeded in a
directory, user must go below the quota during the grace period. If not, the soft 
quota for this particular directory starts to behave like a hard quota.
.SH GENERAL OPTIONS
Most of \fBmfstools\fP use \fB-n\fP, \fB-h\fP, \fB-H\fP, \fB-k\fP, \fB-m\fP and \fB-g\fP
options to select
format of printed numbers. \fB-n\fP causes to print exact numbers, \fB-h\fP
uses binary prefixes (Ki, Mi, Gi as 2^10, 2^20 etc.) while \fB-H\fP uses SI
prefixes (k, M, G as 10^3, 10^6 etc.). \fB-k\fP, \fB-m\fP and \fB-g\fP show plain numbers
respectivaly in kibis (binary kilo - 1024), mebis (binary mega - 1024^2)
and gibis (binary giga - 1024^3).
The same can be achieved by setting
\fBMFSHRFORMAT\fP environment variable to: \fB0\fP (exact numbers), \fB1\fP
or \fBh\fP (binary prefixes), \fB2\fP or \fBH\fP (SI prefixes), \fB3\fP or
\fBh+\fP (exact numbers and binary prefixes), \fB4\fP or \fBH+\fP (exact
numbers and SI prefixes). The default is to print just exact numbers.
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2020 Jakub Kruszona-Zawadzki, Core Technology Sp. z o.o.

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfsmount (8),
.BR mfstools (1)
