.TH mfstools "1" "November 2019" "MooseFS 3.0.109-1" "This is part of MooseFS"
.SH NAME
mfstools \- perform \fBMooseFS\fP\-specific operations
.SH GOAL MANAGEMENT TOOLS
.BR mfsgetgoal ,
.BR mfssetgoal ,
.B mfscopygoal
.SH STORAGE CLASSES MANAGEMENT TOOLS
.BR mfsgetsclass ,
.BR mfssetsclass ,
.BR mfscopysclass ,
.BR mfsxchgsclass ,
.B mfslistsclass
.SH TRASH RETENTION MANAGEMENT TOOLS
.BR mfsgettrashtime ,
.BR mfssettrashtime ,
.B mfscopytrashtime
.SH EXTRA ATTRIBUTES MANAGEMENT TOOLS
.BR mfsgeteattr ,
.BR mfsseteattr ,
.BR mfsdeleattr ,
.B mfscopyeattr
.SH DIAGNOSTIC TOOLS
.BR mfscheckfile ,
.BR mfsfileinfo ,
.BR mfsdirinfo ,
.BR mfsfilepaths ,
.B mfsfilerepair
.SH SNAPSHOT TOOLS
.BR mfsappendchunks ,
.BR mfsmakesnapshot ,
.B mfsrmsnapshot
.SH QUOTA MANAGEMENT TOOLS
.BR mfsgetquota ,
.BR mfssetquota ,
.BR mfsdelquota ,
.B mfscopyquota
.SH GENERAL OPTIONS
Most of \fBmfstools\fP use \fB-n\fP, \fB-h\fP, \fB-H\fP, \fB-k\fP, \fB-m\fP and \fB-g\fP
options to select
format of printed numbers. \fB-n\fP causes to print exact numbers, \fB-h\fP
uses binary prefixes (Ki, Mi, Gi as 2^10, 2^20 etc.) while \fB-H\fP uses SI
prefixes (k, M, G as 10^3, 10^6 etc.). \fB-k\fP, \fB-m\fP and \fB-g\fP show plain numbers
respectivaly in kibis (binary kilo - 1024), mebis (binary mega - 1024^2)
and gibis (binary giga - 1024^3).
The same can be achieved by setting
\fBMFSHRFORMAT\fP environment variable to: \fB0\fP (exact numbers), \fB1\fP
or \fBh\fP (binary prefixes), \fB2\fP or \fBH\fP (SI prefixes), \fB3\fP or
\fBh+\fP (exact numbers and binary prefixes), \fB4\fP or \fBH+\fP (exact
numbers and SI prefixes). The default is to print just exact numbers.
.SH INHERITANCE
When new object is created in MooseFS, attributes such as storage class, trashtime and extra
attributes are inherited from parent directory. So if you set i.e. "noowner"
attribute and storage class to "important" in a directory then every new object created in
this directory will have storage class set to "important" and "noowner" flag set. A newly created
object inherits always the current set of its parent's attributes. Changing a
directory attribute does not affect its already created children. To change
an attribute for a directory and all of its children use \fB-r\fP option.
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright (C) 2019 Jakub Kruszona-Zawadzki, Core Technology Sp. z o.o.

This file is part of MooseFS.

MooseFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2 (only).

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA
or visit http://www.gnu.org/licenses/gpl-2.0.html
.SH "SEE ALSO"
.BR mfsmount (8),
.BR mfsgoal (1),
.BR mfssclass (1),
.BR mfstrashtime (1),
.BR mfseattr (1),
.BR mfssnapshots (1),
.BR mfsdiagtools (1),
.BR mfsscadmin (1)
